name: CI - Banking API

on:
  push:
    branches:
      - main
    paths:
      - "backend/BankingAPI/**"
      - ".github/workflows/ci.yml"

  pull_request:
    branches:
      - main
    paths:
      - "backend/BankingAPI/**"
      - ".github/workflows/ci.yml"

jobs:
  backend-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend/BankingAPI

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build backend
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --configuration Release --no-build
        continue-on-error: true